###############################################################################
#
# author: Christoph Kiefer
# email: christophak@bmb.sdu.dk
#
################################################################################
#'
#' Plot Curves For Testing qPCR Primers
#'
#' @param scheme A pipetting scheeme, e.g., generated by get.pipettingScheme.
#'     Generally a data.frame containing gene, cond, col and row information.
#' @param dil Conditions and corresponding dilution steps. A named vector with
#'     conditions as names and denominator of dilution steps as values.
#' @param notPas Character vector containing wells, that are not to be included
#'     in the analysis.
#'
#' @import dplyr
#' @import ggplot2
#' @import purrr
#' @import ggpmisc
#' @import ggrepel
#'
#' @examples scheme <- get.pipettingScheme(c(paste("gene_", 1:6), paste("housekeeper_", 1:2)),
#'         c(0, 2, 4, "6_NTC", "6_CL", "6_iso", "7_NTC", "7_CL", "7_iso"), 2,
#'         c(2,2,2,3,3,3,3,3,3), 1)
#'     scheme <- import.LCcq("data/example.txt", scheme)
#'     plot.cq(scheme, notPass = "N19")
#'
#' @export
plot.cq <- function(scheme, dil = NULL, notPass = NULL, rep_biol = 1) {

    scheme %>%
        mutate(pos = paste0(row, col)) %>%
        group_by(gene, cond, repl_biol, repl_tech) %>%
        mutate(repl_pcr = as.factor(row_number())) %>%
        ungroup() %>%
        filter(!is.na(cq)) %>%
        mutate(pos = paste0(row, col)) %>%
        mutate(pass = if_else(pos %in% notPass, FALSE, TRUE)) %>%
        filter(repl_biol == rep_biol) %>%
        ggplot(aes(cond, -cq)) +
            geom_jitter(aes(colour = as.factor(repl_tech)), size = .5, width = .1, height = 0) +
            facet_wrap(~gene, scales = "free_y") +
        scale_color_discrete(guide = FALSE) +
        geom_text_repel(aes(label = pos, col = as.factor(if_else(pass, 2, 1))),
            max.iter = 50,
            family = "serif",
            segment.size = .25,
            size = 1.5)

}
