###############################################################################
#
# author: Christoph Kiefer
# email: christophak@bmb.sdu.dk
#
################################################################################
#'
#' Plot Curves For Testing qPCR Primers
#'
#' @param scheme A pipetting scheeme, e.g., generated by get.pipettingScheme.
#'     Generally a data.frame containing gene, cond, col and row information.
#' @param dil Conditions and corresponding dilution steps. A named vector with
#'     conditions as names and denominator of dilution steps as values.
#' @param notPas Character vector containing wells, that are not to be included
#'     in the analysis.
#'
#' @import dplyr
#' @import ggplot2
#' @import purrr
#' @import ggpmisc
#' @import ggrepel
#'
#' @examples scheme <- get.pipettingScheme(paste("primer", 1:7), 1:5, 1, 2, 1, nrow = 10, first_col = 18)
#'     scheme <- import.LCcq("data-raw/primer.txt", scheme, decimal_mark = ',')
#'     dils <- c(1, 6, 36, 216, 1298)
#'     names(dils) <- 1:5
#'     analyse.primers(scheme, dil = dils, notPass = c("J22", "I22"))
#'
#' @export
analyse.primers <- function(scheme, dil = NULL, notPass = NULL) {

    if (is.null(dil)) {
        dil <- 1 / as.numeric(as.character(scheme$cond))
    } else if (is.numeric(dil) && all(unique(scheme$cond) %in% names(dil))) {
        dil <- 1 / dil[scheme$cond]
    }

    cq <- scheme %>%
        mutate(conc = dil,
            pos = paste0(row, col)) %>%
        filter(!is.na(conc)) %>%
        mutate(pass = if_else(pos %in% notPass, FALSE, TRUE))

    cq_pass <- cq %>%
        filter(pass)

    effs <- cq_pass %>%
        split(.$gene) %>%
        map(~ lm(cq ~ log2(conc), data = .)) %>%
        map(~ eff(.$coefficients[2])) %>%
        flatten_dbl() %>%
        as_tibble() %>%
        rename(eff = value) %>%
        mutate(gene = sort(unique(scheme$gene)),
            eff = paste("eff =", round(eff, 3)))

    cq %>%
        filter(conc != 0) %>%
        ggplot(aes(log2(conc), cq)) +
        geom_point(aes(colour = pass), size = .5) +
        facet_wrap(~gene, scales = "free_y") +
        geom_smooth(data = cq_pass, method = "lm", lwd = .25, colour = "red", alpha = 0.15) +
        stat_poly_eq(formula = y ~ x,
            aes(label = paste(..eq.label.., ..rr.label.., sep = "~~~")),
            parse = TRUE, family = "serif", size = 3, colour = "grey30",
            label.x.npc = "left", label.y.npc = "bottom") +
        geom_text(data = effs, mapping = aes(label = eff),
            x = -Inf, y = -Inf,
            hjust = -.5, vjust = -2,
            family = "serif",
            size = 3, colour = "grey30") +
        geom_text_repel(aes(label = pos),
            family = "serif",
            segment.size = .25,
            size = 2) +
        scale_color_discrete(guide = FALSE)

}

#'
#' Calculate Primer Efficiencies
#'
#' @param x slope
#'
eff <- function(x, base = 2) {
    -1 + base^(-1/x)
}
